name: recce
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_lints: ^3.0.0
  http: ^1.2.2
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  cached_network_image: ^3.3.1
  json_annotation: ^4.9.0
  get_it: ^7.7.0
  freezed_annotation: ^2.4.4
  another_flushbar: ^1.12.30
  flutter_secure_storage: ^9.2.2
  freezed: ^2.5.2
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  image_cropper: ^8.0.2
  mime: ^1.0.0
  shared_preferences: ^2.3.2
  get: ^4.6.6
  percent_indicator: ^4.2.3
  flutter_launcher_icons: ^0.13.1
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  # Add fonts here if needed

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
